config/routes.rb
SimpleHighScoreService::Application.routes.draw do
  get "top100_scores/index"

  resources :high_scores
  match 'top_100_scores', :controller => 'top100_scores', :action => 'index'
  match 'top_100_scores.xml', :controller => 'top100_scores', :action => 'index', :format => 'xml'

end

app/models/high_score.rb
class HighScore < ActiveRecord::Base
  attr_accessible :full_name, :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @high_scores }
    end
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
    @high_score = HighScore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @high_score }
    end
  end

  # GET /high_scores/new
  # GET /high_scores/new.json
  def new
    @high_score = HighScore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @high_score }
    end
  end

  # GET /high_scores/1/edit
  def edit
    @high_score = HighScore.find(params[:id])
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(params[:high_score])

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, notice: 'High score was successfully created.' }
        format.json { render json: @high_score, status: :created, location: @high_score }
	format.xml  { render xml: @high_score, status: :created, location: @high_score }
      else
        format.html { render action: "new" }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /high_scores/1
  # PUT /high_scores/1.json
  def update
    @high_score = HighScore.find(params[:id])

    respond_to do |format|
      if @high_score.update_attributes(params[:high_score])
        format.html { redirect_to @high_score, notice: 'High score was successfully updated.' }
        format.json { head :no_content }
	format.xml  { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @high_score.errors, status: :unprocessable_entity }
        format.xml  { render xml: @high_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score = HighScore.find(params[:id])
    @high_score.destroy

    respond_to do |format|
      format.html { redirect_to high_scores_url }
      format.json { head :no_content }
      format.xml  { head :no_content }
    end
  end
end

app/controllers/top100_scores_controller.rb
class Top100ScoresController < ApplicationController
  #GET / top100_scores
  #GET / top100_scores .xml
  def index
	@high_scores = HighScore.find(:all, :limit => 100, :order => 'score desc')

	respond_to do |format|
		format.html # index.html.erb
		format.xml { render :xml => @high_scores }
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/helpers/top100_scores_helper.rb
module Top100ScoresHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing high_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<h1>Listing high_scores</h1>

<table>
  <tr>
    <th>Score</th>
    <th>Full name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @high_scores.each do |high_score| %>
  <tr>
    <td><%= high_score.score %></td>
    <td><%= high_score.full_name %></td>
    <td><%= link_to 'Show', high_score %></td>
    <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
    <td><%= link_to 'Destroy', high_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high_score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @high_score.score %>
</p>

<p>
  <b>Full name:</b>
  <%= @high_score.full_name %>
</p>


<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleHighScoreService</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/top100_scores/index.html.erb
<h1>Top100Scores</h1>

<table>
	<tr>
		<th>Score</th>
		<th>Full name</th>
	</tr>

<% for high_score in @high_scores %>
	<tr>
		<td><%=h high_score.score %></td>
		<td><%=h high_score.full_name %></td>
	</tr>

<% end %>
</table>
<br />